---
apiVersion: v1
kind: Service
metadata:
  name: sample-grpc
  namespace: default
  annotations: # Sample ambassador annotation
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  sample_grpc_mapping
      grpc: True
      prefix: /hello.Greeter/
      rewrite: /hello.Greeter/
      service: sample-grpc:8888
spec:
  selector:
    app: sample-grpc
  ports:
  - port: 8888
    name: http-grpc
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-grpc
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-grpc
    spec:
      containers:
      - name: sample-grpc
        image: abhishek627/sample-grpc:latest
        ports:
        - name: http-api
          containerPort: 8888 
